- CHANGELOG.md
- Dockerfile
* chore(Dockerfile): comment out cargo binstall pcu command and add cargo install command for pcu from git repository
> chore: Use un-published version of pcu

- .circleci/config.yml
- CHANGELOG.md
* style(config.yml): remove trailing whitespaces
* feat(config.yml): add rust version 1.76 to min-rust-version list
> feat: add rust version 1.76

- .circleci/config.yml
- CHANGELOG.md
* fix(config.yml): remove unused build-arg in docker build command
* fix(config.yml): change docker push tag from variable TAG to base
> ci: fix docker argument and docker push for missing TAG

- .circleci/config.yml
- CHANGELOG.md
* feat(.circleci/config.yml): add conditional for pipeline trigger source
* feat(.circleci/config.yml): add publish-only job for main branch
> ci: add back in publish workflow

- .circleci/config.yml
- CHANGELOG.md
* feat(config.yml): add rust-env executor
* chore(config.yml): remove gpg-key and git-config commands
* feat(config.yml): add make_release job
* chore(config.yml): remove pr-changelog-update job
* refactor(config.yml): update make_release job in workflows
> feat: make release to increment version number and update change log

- .circleci/config.yml
- CHANGELOG.md
* chore(.circleci/config.yml): add pipeline flag to set command
* feat(.circleci/config.yml): add echo command to display version
* fix(.circleci/config.yml): change filename from lowercase to uppercase in git add command
* feat(.circleci/config.yml): add git push --tags command after gh release create command
> fix: changelog to CHANGELOG and better debugging

- .circleci/config.yml
- CHANGELOG.md
* feat(.circleci/config.yml): add pcu_verbosity parameter with default value
* chore(.circleci/config.yml): update pcu release command to use pcu_verbosity parameter
* chore(.circleci/config.yml): add tree, head and git status commands to release job
* feat(.circleci/config.yml): add pcu_verbosity parameter to workflows
> ci: add pcu_verbosity parameter and update pcu release command

- .circleci/config.yml
- CHANGELOG.md
* chore(config.yml): replace 'tree' command with 'ls -l'
* fix(config.yml): change release notes file from CHANGELOG.md to release_notes.md in gh release create command
> ci: replace tree with ls

- .circleci/config.yml
- CHANGELOG.md
* chore(circleci/config.yml): upgrade toolkit version to 0.25.0
* feat(circleci/config.yml): add tag_log parameter to workflows
> ci: update to toolkit 0.25.0 and enable tag_log in release workflow

- .circleci/config.yml
- CHANGELOG.md
* chore(circleci/config.yml): update toolkit version from 0.25.0 to 0.27.0
* refactor(circleci/config.yml): rename tag_log to pcu_update_changelog
> ci: update toolkit version from 0.25.0 to 0.27.0 and set pcu_update_changelog to true

- .circleci/config.yml
- CHANGELOG.md
* refactor(config.yml): rename publish_rustcs to publish_rustc_version
* feat(config.yml): add support for rustc version 1.79
> feat: add support for rustc version 1.79

- .circleci/config.yml
- CHANGELOG.md
- sonar-project.properties
ci(sonar): add sonar-project properties file for SonarCloud integration
> ci(circleci): update toolkit orb version and add security context

- .circleci/config.yml
- CHANGELOG.md
- introduce release-flag parameter to trigger the release pipeline
- update workflows to check release-flag for conditional execution
- enhance flexibility in controlling pipeline execution paths
> ci(circleci): add release-flag parameter for pipeline execution

- .circleci/config.yml
- add additional condition to exclude release-flag triggered workflows
- improve workflow execution control with enhanced checks
> ci(circleci): refine check_rebase workflow conditions

- CHANGELOG.md
- Dockerfile
- bump nextsv version from 0.19.10 to 0.19.11 for latest features and fixes
> 🔧 chore(Dockerfile): update nextsv version to 0.19.11

- CHANGELOG.md
- renovate.json
- eliminate specific schedule for renovate updates
- simplify renovate.json configuration
> 🔧 chore(config): remove renovate schedule

- .circleci/config.yml
- CHANGELOG.md
- add tag filters to ensure jobs run only on tag events
- restructure workflows by moving make_release job and adding deploy workflow
- apply filters to all relevant jobs for consistent execution conditions
> 👷 ci(circleci): update workflow configurations for release and deploy

- CHANGELOG.md
- Dockerfile
- bump pcu version from 0.4.41 to 0.4.42 for latest updates and fixes
> 🔧 chore(Dockerfile): update pcu version to 0.4.42

- .circleci/config.yml
- CHANGELOG.md
- upgrade toolkit orb from version 2.10.7 to 2.10.8 for latest features and fixes
> 🔧 chore(ci): update CircleCI toolkit orb version

- .circleci/config.yml
- CHANGELOG.md
- adjust list indentation for min-rust-version to ensure proper YAML parsing
> 👷 ci(circleci): fix YAML formatting for matrix parameters

- .circleci/config.yml
- .vscode/settings.json
- CHANGELOG.md
- Dockerfile
- upgrade toolkit orb from version 2.10.9 to 2.11.0 for latest features
🌐 i18n(vscode): add sonarlint project connection
- configure sonarlint connected mode for project key "jerus-org_ci-container"
♻️ refactor(dockerfile): optimize Dockerfile dependencies and commands
- update PCU_VERSION to 0.4.46
- reorder package installation for better dependency resolution
- clean up apt lists to reduce image size
- ensure consistent use of quotes for environment variables
> 👷 ci(circleci): update circleci-toolkit orb version

- .circleci/config.yml
- CHANGELOG.md
- add Rust version 1.87 to the matrix for testing compatibility
> 👷 ci(circleci): update Rust version matrix

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- Makefile
- test.sh
- add project directory listing for better visibility
- include current and home directory contents in logs
> 🔧 chore(makefile): enhance build scripts with logging

- .vscode/settings.json
- Dockerfile
- PRLOG.md
- add new environment variables for circleci_junit_fix and gen-changelog
- reorganize cargo binstall commands for better readability
- update and lock versions for specific cargo packages
> 📦 build(dockerfile): update and reorganize cargo dependencies

- .circleci/config.yml
- PRLOG.md
- correct spacing in if statement for crate parameter check
> 👷 ci(circleci): fix syntax error in config.yml

- .circleci/config.yml
- PRLOG.md
- enable conditional execution for PCU updates in CircleCI configuration
> 👷 ci(circleci): add when_update_pcu parameter to workflows

- .circleci/config.yml
- PRLOG.md
- correct the update_prlog flag from --update-changelog to --update-prlog for accurate script execution in CI pipeline
> 👷 ci(circleci): fix update_prlog flag in config

- .circleci/config.yml
- Dockerfile
- PRLOG.md
- bump gen-changelog version from 0.1.0 to 0.1.1 for latest features and fixes
> 🔧 chore(Dockerfile): update gen-changelog version

- .circleci/config.yml
- PRLOG.md
- remove unused parameters when_update_pcu and when_install_rust_crate
- clean up config for better maintainability
> 👷 ci(circleci): update configuration for workflow parameters

- Dockerfile
- PRLOG.md
- bump gen-changelog version from 0.1.1 to 0.1.2
> 📦 build(dockerfile): update gen-changelog version

- Dockerfile
- PRLOG.md
- bump gen-changelog version from 0.1.2 to 0.1.3 for latest features and fixes
> 📦 build(Dockerfile): update gen-changelog version to 0.1.3
